name: CD Dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nextunelk-server
  IMAGE_NAME_CLIENT: ${{ github.repository }}/nextunelk-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # lowercase the image name
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV
          echo "IMAGE_NAME_CLIENT=${IMAGE_NAME_CLIENT,,}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev

      - name: Build and push Client Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}:dev
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=https://dev-api.ishanardithya.me:8443/nextunelk

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Logging into Registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "Pulling latest images..."
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}:dev
            
            # --- Deploy Server ---
            echo "Deploying Server..."
            docker stop nextunelk-server-dev || true
            docker rm nextunelk-server-dev || true
            
            docker run -d \
              --name nextunelk-server-dev \
              --restart unless-stopped \
              --network host \
              --env-file .env.nextunelk \
              -v $HOME/logs:/app/logs \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev

            # --- Deploy Client ---
            echo "Deploying Client..."
            docker stop nextunelk-client-dev || true
            docker rm nextunelk-client-dev || true
            
            docker run -d \
              --name nextunelk-client-dev \
              --restart unless-stopped \
              -p 3006:3000 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}:dev
            
            echo "Deployment successful."
